deploy:
  provider: pypi
  username: "__token__"
  password: "pypi-AgEIcHlwaS5vcmcCJDVlYTA5MTU3LTAxNWQtNGQzNS1iMTQ5LTMxM2U0OTA4MzRiMQACKlszLCI5NjFlZmYxZC00ODc1LTQ0YWMtODcwZC0wOTc2OGRiMjcwOWUiXQAABiDvQz1Rn_vCOZXDirvw-xnvINAr9qSxtmG3Cz3yYNWQtQ"
  on:
    branch: 
      master